services:
  - type: web
    name: owais-anime-stream
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: SHIELD_SECRET
        generateValue: true
      - key: RESOLVER_BASE
        sync: false
      - key: RESOLVER_KEY
        sync: false
