plugins {
    id 'com.android.application'
}

android {
    namespace 'com.owais.anime'
    compileSdk 35

    defaultConfig {
        applicationId 'com.owais.anime'
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName '4.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-exoplayer-hls:1.8.0'
    implementation 'androidx.media3:media3-ui:1.8.0'
}
